cmake_minimum_required(VERSION 3.16)
project(imu_review)
set(CMAKE_CXX_STANDARD 17)
find_package(ament_cmake REQUIRED)
find_package(rosbag2_cpp REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
add_executable(imu_review main.cpp)
ament_target_dependencies(imu_review rosbag2_cpp rclcpp sensor_msgs)
